/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.admin;

import control.InitialStatelessLogin;
import control.LoggingFunction;
import edu.tdt.service.SystemLoginRemote;
import java.awt.Toolkit;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import views.login.Login;
import views.student.ChangePassword;

/**
 *
 * @author HAU
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form AdminView
     */
    Login x;
    LoggingFunction logging;
    String filename;
    SimpleDateFormat sdf;
    Date date_event;
    InitialStatelessLogin init;

    public AdminView() {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        double width = toolkit.getScreenSize().getWidth();
        double height = toolkit.getScreenSize().getHeight();
        this.setSize((int) width, (int) height);
        initComponents();
        init = new InitialStatelessLogin();
        x = new Login();
        logging = new LoggingFunction();
        filename = "log.txt";
        sdf = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        jLabel1.setText("Hello " + x.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogout = new javax.swing.JLabel();
        jLabelChangePw = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuStudent = new javax.swing.JMenu();
        jMenuNewStudent = new javax.swing.JMenuItem();
        jMenuEditStudent = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuCreateMark = new javax.swing.JMenuItem();
        jMenuEditMark = new javax.swing.JMenuItem();
        jMenuFee = new javax.swing.JMenu();
        jMenuCheckFee = new javax.swing.JMenuItem();
        jMenuRequest = new javax.swing.JMenu();
        jMenuEditRequest = new javax.swing.JMenuItem();
        jMenuCourse = new javax.swing.JMenu();
        jMenuNewCourse = new javax.swing.JMenuItem();
        jMenuEditCourse = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuRegisterCourse = new javax.swing.JMenuItem();
        jMenuListCoursesRegistered = new javax.swing.JMenuItem();
        jMenuRoom = new javax.swing.JMenu();
        jMenuNewRoom = new javax.swing.JMenuItem();
        jMenuEditRoom = new javax.swing.JMenuItem();
        jMenuItemViewRoom = new javax.swing.JMenuItem();
        jMenuTeacher = new javax.swing.JMenu();
        jMenuNewTeacher = new javax.swing.JMenuItem();
        jMenuEditTeacher = new javax.swing.JMenuItem();
        jMenuTool = new javax.swing.JMenu();
        jMenuCalculator = new javax.swing.JMenuItem();
        jMenuNote = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin");
        setIconImages(getIconImages());
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabelLogout.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-exit-26.png"))); // NOI18N
        jLabelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoutMouseClicked(evt);
            }
        });

        jLabelChangePw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelChangePw.setText("Change Password");
        jLabelChangePw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelChangePwMouseClicked(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelLogout, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelChangePw, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(1021, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLogout))
                    .addComponent(jLabelChangePw, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelChangePw)
                .addGap(0, 627, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jMenuStudent.setText("Student details");
        jMenuStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuNewStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jMenuNewStudent.setText("New Student");
        jMenuNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewStudentActionPerformed(evt);
            }
        });
        jMenuStudent.add(jMenuNewStudent);

        jMenuEditStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editreg.png"))); // NOI18N
        jMenuEditStudent.setText("Edit Student");
        jMenuEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditStudentActionPerformed(evt);
            }
        });
        jMenuStudent.add(jMenuEditStudent);
        jMenuStudent.add(jSeparator2);

        jMenuCreateMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marklist.png"))); // NOI18N
        jMenuCreateMark.setText("Create Mark");
        jMenuCreateMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCreateMarkActionPerformed(evt);
            }
        });
        jMenuStudent.add(jMenuCreateMark);

        jMenuEditMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editmark.png"))); // NOI18N
        jMenuEditMark.setText("Edit Mark");
        jMenuEditMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditMarkActionPerformed(evt);
            }
        });
        jMenuStudent.add(jMenuEditMark);

        jMenuBar1.add(jMenuStudent);

        jMenuFee.setText("Fee Details");
        jMenuFee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuCheckFee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        jMenuCheckFee.setText("Check Fee");
        jMenuCheckFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCheckFeeActionPerformed(evt);
            }
        });
        jMenuFee.add(jMenuCheckFee);

        jMenuBar1.add(jMenuFee);

        jMenuRequest.setText("Request details");
        jMenuRequest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuEditRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        jMenuEditRequest.setText("Edit Request");
        jMenuEditRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditRequestActionPerformed(evt);
            }
        });
        jMenuRequest.add(jMenuEditRequest);

        jMenuBar1.add(jMenuRequest);

        jMenuCourse.setText("Course details");
        jMenuCourse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuNewCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newreg.png"))); // NOI18N
        jMenuNewCourse.setText("New Course");
        jMenuNewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewCourseActionPerformed(evt);
            }
        });
        jMenuCourse.add(jMenuNewCourse);

        jMenuEditCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marklist.png"))); // NOI18N
        jMenuEditCourse.setText("Edit Course");
        jMenuEditCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditCourseActionPerformed(evt);
            }
        });
        jMenuCourse.add(jMenuEditCourse);
        jMenuCourse.add(jSeparator1);

        jMenuRegisterCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editmark.png"))); // NOI18N
        jMenuRegisterCourse.setText("Register Course For Student ");
        jMenuRegisterCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegisterCourseActionPerformed(evt);
            }
        });
        jMenuCourse.add(jMenuRegisterCourse);

        jMenuListCoursesRegistered.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        jMenuListCoursesRegistered.setText("List Course Registered");
        jMenuListCoursesRegistered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListCoursesRegisteredActionPerformed(evt);
            }
        });
        jMenuCourse.add(jMenuListCoursesRegistered);

        jMenuBar1.add(jMenuCourse);

        jMenuRoom.setText("Room Details");
        jMenuRoom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuNewRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/memlist.png"))); // NOI18N
        jMenuNewRoom.setText("New Room");
        jMenuNewRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewRoomActionPerformed(evt);
            }
        });
        jMenuRoom.add(jMenuNewRoom);

        jMenuEditRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        jMenuEditRoom.setText("Edit Room");
        jMenuEditRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditRoomActionPerformed(evt);
            }
        });
        jMenuRoom.add(jMenuEditRoom);

        jMenuItemViewRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        jMenuItemViewRoom.setText("View Room");
        jMenuItemViewRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewRoomActionPerformed(evt);
            }
        });
        jMenuRoom.add(jMenuItemViewRoom);

        jMenuBar1.add(jMenuRoom);

        jMenuTeacher.setText("Teacher details");
        jMenuTeacher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuNewTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stddet.png"))); // NOI18N
        jMenuNewTeacher.setText("New Teacher");
        jMenuNewTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewTeacherActionPerformed(evt);
            }
        });
        jMenuTeacher.add(jMenuNewTeacher);

        jMenuEditTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/appicon.PNG"))); // NOI18N
        jMenuEditTeacher.setText("Edit Teacher");
        jMenuEditTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditTeacherActionPerformed(evt);
            }
        });
        jMenuTeacher.add(jMenuEditTeacher);

        jMenuBar1.add(jMenuTeacher);

        jMenuTool.setText("Tools");
        jMenuTool.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calc.png"))); // NOI18N
        jMenuCalculator.setText("Calculator");
        jMenuCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCalculatorActionPerformed(evt);
            }
        });
        jMenuTool.add(jMenuCalculator);

        jMenuNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notepad.png"))); // NOI18N
        jMenuNote.setText("Note");
        jMenuNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNoteActionPerformed(evt);
            }
        });
        jMenuTool.add(jMenuNote);

        jMenuBar1.add(jMenuTool);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNewStudentActionPerformed
        //Write event to log.txt
        date_event = new Date();
        sdf.format(date_event);
        logging.writeFileLog(filename, date_event + " " + x.getUserID() + " click menu New Student\n");

        NewStdReg frm = new NewStdReg();
        jDesktopPane1.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuNewStudentActionPerformed

    private void jMenuEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditStudentActionPerformed
        //Write event to log.txt
        date_event = new Date();
        sdf.format(date_event);
        logging.writeFileLog(filename, date_event + " " + x.getUserID() + " click menu Edit Student\n");

        EditStdReg frm = new EditStdReg();
        jDesktopPane1.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuEditStudentActionPerformed

    private void jMenuEditMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditMarkActionPerformed
        //Write event to log.txt
        date_event = new Date();
        sdf.format(date_event);
        logging.writeFileLog(filename, date_event + " " + x.getUserID() + " click menu Edit Student\n");

        EditMark frm = new EditMark();
        jDesktopPane1.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuEditMarkActionPerformed

    private void jMenuCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCalculatorActionPerformed
        try {
            //Write event to log.txt
            date_event = new Date();
            sdf.format(date_event);
            logging.writeFileLog(filename, date_event + " " + x.getUserID() + " open Calculator\n");

            Runtime.getRuntime().exec("calc.exe");
        } catch (IOException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuCalculatorActionPerformed

    private void jMenuNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNoteActionPerformed
        try {
            //Write event to log.txt
            date_event = new Date();
            sdf.format(date_event);
            logging.writeFileLog(filename, date_event + " " + x.getUserID() + " open Notepad\n");

            Runtime.getRuntime().exec("notepad.exe");
        } catch (IOException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuNoteActionPerformed

    private void jMenuEditRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditRequestActionPerformed
        //Write event to log.txt
        date_event = new Date();
        sdf.format(date_event);
        logging.writeFileLog(filename, date_event + " " + x.getUserID() + " click menu Edit Request\n");

        EditRequest frm = new EditRequest();
        jDesktopPane1.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuEditRequestActionPerformed

    private void jLabelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMouseClicked
        try {
            SystemLoginRemote session = (SystemLoginRemote) init.getCtx().lookup(init.getJNDI());
            session.update_State(x.getUserID(), false);
            //Write event to log.txt
            date_event = new Date();
            sdf.format(date_event);
            logging.writeFileLog(filename, date_event + " " + x.getUserID() + " logout system\n");

            new Login().setVisible(true);
            this.dispose();
        } catch (NamingException ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelLogoutMouseClicked

    private void jLabelChangePwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelChangePwMouseClicked
        new ChangePassword().setVisible(true);
    }//GEN-LAST:event_jLabelChangePwMouseClicked

    private void jMenuNewTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNewTeacherActionPerformed
        //Write event to log.txt
        date_event = new Date();
        sdf.format(date_event);
        logging.writeFileLog(filename, date_event + " " + x.getUserID() + " click menu New Teacher\n");

        NewTeacherReg frm = new NewTeacherReg();
        jDesktopPane1.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuNewTeacherActionPerformed

    private void jMenuEditTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditTeacherActionPerformed
        //Write event to log.txt
        date_event = new Date();
        sdf.format(date_event);
        logging.writeFileLog(filename, date_event + " " + x.getUserID() + " click menu Edit Teacher\n");

        EditTeacherReg frm = new EditTeacherReg();
        jDesktopPane1.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuEditTeacherActionPerformed

    private void jMenuNewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNewCourseActionPerformed
        //Write event to log.txt
        date_event = new Date();
        sdf.format(date_event);
        logging.writeFileLog(filename, date_event + " " + x.getUserID() + " click menu New Course\n");

        NewCourseReg frm = new NewCourseReg();
        jDesktopPane1.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuNewCourseActionPerformed

    private void jMenuRegisterCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegisterCourseActionPerformed
        //Write event to log.txt
        date_event = new Date();
        sdf.format(date_event);
        logging.writeFileLog(filename, date_event + " " + x.getUserID() + " click menu Register Course\n");

        RegisterCourse frm = new RegisterCourse();
        jDesktopPane1.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuRegisterCourseActionPerformed

    private void jMenuNewRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNewRoomActionPerformed
        //Write event to log.txt
        date_event = new Date();
        sdf.format(date_event);
        logging.writeFileLog(filename, date_event + " " + x.getUserID() + " click menu New Room\n");

        NewRoomReg frm = new NewRoomReg();
        jDesktopPane1.add(frm);
        frm.setVisible(true);

    }//GEN-LAST:event_jMenuNewRoomActionPerformed

    private void jMenuEditRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditRoomActionPerformed
        //Write event to log.txt
        date_event = new Date();
        sdf.format(date_event);
        logging.writeFileLog(filename, date_event + " " + x.getUserID() + " click menu Edit Room\n");

        EditRoomReg frm = new EditRoomReg();
        jDesktopPane1.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuEditRoomActionPerformed

    private void jMenuCreateMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCreateMarkActionPerformed
        //Write event to log.txt
        date_event = new Date();
        sdf.format(date_event);
        logging.writeFileLog(filename, date_event + " " + x.getUserID() + " click menu Create Mark\n");

        CreateMark frm = new CreateMark();
        jDesktopPane1.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuCreateMarkActionPerformed

    private void jMenuCheckFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCheckFeeActionPerformed
        //Write event to log.txt
        date_event = new Date();
        sdf.format(date_event);
        logging.writeFileLog(filename, date_event + " " + x.getUserID() + " click menu View Fee\n");

        ViewFee frm = new ViewFee();
        jDesktopPane1.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuCheckFeeActionPerformed

    private void jMenuEditCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditCourseActionPerformed
        //Write event to log.txt
        date_event = new Date();
        sdf.format(date_event);
        logging.writeFileLog(filename, date_event + " " + x.getUserID() + " click menu Edit Course\n");

        EditCourseReg frm = new EditCourseReg();
        jDesktopPane1.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuEditCourseActionPerformed

    private void jMenuListCoursesRegisteredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListCoursesRegisteredActionPerformed
        //Write event to log.txt
        date_event = new Date();
        sdf.format(date_event);
        logging.writeFileLog(filename, date_event + " " + x.getUserID() + " click menu List Courses Registered\n");

        ViewCoursesRegistered frm = new ViewCoursesRegistered();
        jDesktopPane1.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuListCoursesRegisteredActionPerformed

    private void jMenuItemViewRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewRoomActionPerformed
        //Write event to log.txt
        date_event = new Date();
        sdf.format(date_event);
        logging.writeFileLog(filename, date_event + " " + x.getUserID() + " click menu View Room\n");

        RoomView frm = new RoomView();
        jDesktopPane1.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItemViewRoomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            AdminView frm = new AdminView();
            frm.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelChangePw;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCalculator;
    private javax.swing.JMenuItem jMenuCheckFee;
    private javax.swing.JMenu jMenuCourse;
    private javax.swing.JMenuItem jMenuCreateMark;
    private javax.swing.JMenuItem jMenuEditCourse;
    private javax.swing.JMenuItem jMenuEditMark;
    private javax.swing.JMenuItem jMenuEditRequest;
    private javax.swing.JMenuItem jMenuEditRoom;
    private javax.swing.JMenuItem jMenuEditStudent;
    private javax.swing.JMenuItem jMenuEditTeacher;
    private javax.swing.JMenu jMenuFee;
    private javax.swing.JMenuItem jMenuItemViewRoom;
    private javax.swing.JMenuItem jMenuListCoursesRegistered;
    private javax.swing.JMenuItem jMenuNewCourse;
    private javax.swing.JMenuItem jMenuNewRoom;
    private javax.swing.JMenuItem jMenuNewStudent;
    private javax.swing.JMenuItem jMenuNewTeacher;
    private javax.swing.JMenuItem jMenuNote;
    private javax.swing.JMenuItem jMenuRegisterCourse;
    private javax.swing.JMenu jMenuRequest;
    private javax.swing.JMenu jMenuRoom;
    private javax.swing.JMenu jMenuStudent;
    private javax.swing.JMenu jMenuTeacher;
    private javax.swing.JMenu jMenuTool;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
