/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.admin;

import control.InitialStatelessStudentOrAdmin;
import edu.tdt.entity.Room;
import edu.tdt.service.SystemStudentManagementRemote;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HAU
 */
public class EditRoomReg extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegisterCourse
     */
    InitialStatelessStudentOrAdmin init;
    DefaultTableModel dftable1;
    DefaultTableModel dftable2;

    public EditRoomReg() {
        initComponents();
        init = new InitialStatelessStudentOrAdmin();
        dftable1 = (DefaultTableModel) jDataTable.getModel();
        dftable2 = (DefaultTableModel) jDataTable1.getModel();
        loadDataOnJComboBox();
    }

    private void loadDataOnJComboBox() {
        try {
            SystemStudentManagementRemote session = (SystemStudentManagementRemote) init.getCtx().lookup(init.getJNDI());
            List<Object[]> roomList = session.getIDRooms();
            for (int i = 0; i < roomList.size(); i++) {
                String room = (String) roomList.get(i)[0];
                jComboBoxRoom.addItem(room);
            }
        } catch (NamingException ex) {
            Logger.getLogger(EditRoomReg.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadCoursesOnJTable() {
        try {
            dftable1.setRowCount(0);

            SystemStudentManagementRemote session = (SystemStudentManagementRemote) init.getCtx().lookup(init.getJNDI());
            List<Object[]> courses = session.getCourses();

            for (int i = 0; i < courses.size(); i++) {
                String id_course = courses.get(i)[0].toString();
                String name = courses.get(i)[1].toString();
                String duration = courses.get(i)[2].toString();
                String fee = courses.get(i)[3].toString();
                String type = courses.get(i)[4].toString();

                Object[] ojb = {id_course, name, duration, fee, type};
                dftable1.addRow(ojb);
            }
        } catch (NamingException ex) {
            Logger.getLogger(EditRoomReg.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadTeachersOnJTable() {
        try {
            dftable2.setRowCount(0);
            SimpleDateFormat formatter1 = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat formatter2 = new SimpleDateFormat("yyyy-MM-dd");

            SystemStudentManagementRemote session = (SystemStudentManagementRemote) init.getCtx().lookup(init.getJNDI());
            List<Object[]> teachers = session.getAllTeachers();

            for (int i = 0; i < teachers.size(); i++) {
                String id_student = teachers.get(i)[0].toString();
                String fullname = teachers.get(i)[2].toString() + " " + teachers.get(i)[1].toString();
                String student_birthday = formatter1.format(formatter2.parse(teachers.get(i)[3].toString()));
                String gender = ("true".equals(teachers.get(i)[4].toString())) ? "Male" : "Female";
                String email = teachers.get(i)[6].toString();

                Object[] ojb = {id_student, fullname, student_birthday, gender, email};
                dftable2.addRow(ojb);
            }
        } catch (NamingException | ParseException ex) {
            Logger.getLogger(EditRoomReg.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLoadData2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDataTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDataTable1 = new javax.swing.JTable();
        jLabelTitle = new javax.swing.JLabel();
        jPanel = new javax.swing.JPanel();
        jLabelIDCourse = new javax.swing.JLabel();
        jTextFieldIDCourse = new javax.swing.JTextField();
        jLabelNameCourse = new javax.swing.JLabel();
        jTextFieldNameCourse = new javax.swing.JTextField();
        jLabelType = new javax.swing.JLabel();
        jTextFieldType = new javax.swing.JTextField();
        jLabelIDTeacher = new javax.swing.JLabel();
        jTextFieldIDTeacher = new javax.swing.JTextField();
        jLabelNameTeacher = new javax.swing.JLabel();
        jTextFieldNameTeacher = new javax.swing.JTextField();
        JLabelBirthday = new javax.swing.JLabel();
        jTextFieldBirthday = new javax.swing.JTextField();
        jLabelIDRoom = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jTextFieldStartDate = new javax.swing.JTextField();
        jLabelSession = new javax.swing.JLabel();
        jTextFieldSession = new javax.swing.JTextField();
        jComboBoxRoom = new javax.swing.JComboBox<>();
        jButtonLoad = new javax.swing.JButton();
        jButtonLoadData1 = new javax.swing.JButton();
        jButtonCreate = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Edit Room");

        jButtonLoadData2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonLoadData2.setText("Load");
        jButtonLoadData2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoadData2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoadData2MouseExited(evt);
            }
        });
        jButtonLoadData2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadData2ActionPerformed(evt);
            }
        });

        jDataTable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Duration", "Fee", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jDataTable.setRowHeight(30);
        jDataTable.setRowMargin(2);
        jDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jDataTable);

        jDataTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jDataTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Full Name", "Birthday", "Gender", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jDataTable1.setRowHeight(30);
        jDataTable1.setRowMargin(2);
        jDataTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDataTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jDataTable1);

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 51, 204));
        jLabelTitle.setText("EDIT ROOM");

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setPreferredSize(new java.awt.Dimension(1920, 402));

        jLabelIDCourse.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelIDCourse.setText("ID Course");

        jTextFieldIDCourse.setEditable(false);
        jTextFieldIDCourse.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIDCourse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelNameCourse.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelNameCourse.setText("Name");

        jTextFieldNameCourse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelType.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelType.setText("Type");

        jTextFieldType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelIDTeacher.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelIDTeacher.setText("ID Teacher");

        jTextFieldIDTeacher.setEditable(false);
        jTextFieldIDTeacher.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIDTeacher.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelNameTeacher.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelNameTeacher.setText("Full Name");

        jTextFieldNameTeacher.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        JLabelBirthday.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLabelBirthday.setText("Birthday");

        jTextFieldBirthday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelIDRoom.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelIDRoom.setText("ID Room");

        jLabelDate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelDate.setText("Start");

        jTextFieldStartDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelSession.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelSession.setText("Session");

        jTextFieldSession.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jComboBoxRoom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jButtonLoad.setBackground(new java.awt.Color(12, 91, 160));
        jButtonLoad.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonLoad.setText("Load");
        jButtonLoad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoadMouseExited(evt);
            }
        });
        jButtonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jTextFieldIDCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248)
                        .addComponent(jComboBoxRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButtonLoad)
                        .addGap(137, 137, 137)
                        .addComponent(jTextFieldIDTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabelNameCourse)
                        .addGap(470, 470, 470)
                        .addComponent(jLabelDate)
                        .addGap(462, 462, 462)
                        .addComponent(jLabelNameTeacher))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(jTextFieldNameCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(390, 390, 390)
                                .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(290, 290, 290)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(390, 390, 390)
                                .addComponent(jTextFieldNameTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabelSession)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JLabelBirthday)
                                .addGap(147, 147, 147))))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(jTextFieldSession, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(150, 150, 150)
                        .addComponent(jTextFieldBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jLabelIDCourse)
                .addGap(421, 421, 421)
                .addComponent(jLabelIDRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelIDTeacher)
                .addGap(298, 298, 298))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIDCourse)
                            .addComponent(jLabelIDRoom)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelIDTeacher)))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIDCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldIDTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonLoad))))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNameCourse)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelDate))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelNameTeacher)))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNameCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNameTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelType)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSession, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLabelBirthday, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSession, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jButtonLoadData1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonLoadData1.setText("Load");
        jButtonLoadData1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoadData1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoadData1MouseExited(evt);
            }
        });
        jButtonLoadData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadData1ActionPerformed(evt);
            }
        });

        jButtonCreate.setBackground(new java.awt.Color(12, 91, 160));
        jButtonCreate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonCreate.setText("Create");
        jButtonCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCreateMouseExited(evt);
            }
        });
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });

        jButtonReset.setBackground(new java.awt.Color(12, 91, 160));
        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonResetMouseExited(evt);
            }
        });
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jButtonLoadData1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLoadData2)
                .addGap(221, 221, 221))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1877, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(849, 849, 849)
                        .addComponent(jButtonCreate)
                        .addGap(66, 66, 66)
                        .addComponent(jButtonReset)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addGap(832, 832, 832))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitle)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLoadData2)
                    .addComponent(jButtonLoadData1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreate)
                    .addComponent(jButtonReset))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDataTableMouseClicked
        int selectedIndexRow = jDataTable.getSelectedRow();

        jTextFieldIDCourse.setText(dftable1.getValueAt(selectedIndexRow, 0).toString());
        jTextFieldNameCourse.setText(dftable1.getValueAt(selectedIndexRow, 1).toString());
        jTextFieldType.setText(dftable1.getValueAt(selectedIndexRow, 2).toString());
    }//GEN-LAST:event_jDataTableMouseClicked

    private void jDataTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDataTable1MouseClicked
        int selectedIndexRow = jDataTable1.getSelectedRow();

        jTextFieldIDTeacher.setText(dftable2.getValueAt(selectedIndexRow, 0).toString());
        jTextFieldNameTeacher.setText(dftable2.getValueAt(selectedIndexRow, 1).toString());
        jTextFieldBirthday.setText(dftable2.getValueAt(selectedIndexRow, 2).toString());

    }//GEN-LAST:event_jDataTable1MouseClicked

    private void jButtonLoadData2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadData2ActionPerformed
        loadTeachersOnJTable();
    }//GEN-LAST:event_jButtonLoadData2ActionPerformed

    private void jButtonLoadData2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoadData2MouseEntered
        setColor(jButtonLoadData2);
    }//GEN-LAST:event_jButtonLoadData2MouseEntered

    private void jButtonLoadData2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoadData2MouseExited
        resetColor(jButtonLoadData2);
    }//GEN-LAST:event_jButtonLoadData2MouseExited

    private void jButtonLoadData1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoadData1MouseEntered
        setColor(jButtonLoadData1);
    }//GEN-LAST:event_jButtonLoadData1MouseEntered

    private void jButtonLoadData1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoadData1MouseExited
        resetColor(jButtonLoadData1);
    }//GEN-LAST:event_jButtonLoadData1MouseExited

    private void jButtonLoadData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadData1ActionPerformed
        loadCoursesOnJTable();
    }//GEN-LAST:event_jButtonLoadData1ActionPerformed

    private void jButtonCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateMouseEntered
        setColor(jButtonCreate);
    }//GEN-LAST:event_jButtonCreateMouseEntered

    private void jButtonCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateMouseExited
        resetColor(jButtonCreate);
    }//GEN-LAST:event_jButtonCreateMouseExited

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        try {
            SystemStudentManagementRemote session = (SystemStudentManagementRemote) init.getCtx().lookup(init.getJNDI());
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
            
            //Get start date of room from combobox
            Date date;

            String start_date = jTextFieldStartDate.getText();            
            
            date = formatter.parse(start_date);           
            Room room = new Room();            
            room.setId(jComboBoxRoom.getSelectedItem().toString());
            room.setStartDate(date);
            room.setSession(Integer.parseInt(jTextFieldSession.getText()));
            
            session.updateRoom(room, jTextFieldIDCourse.getText(), jTextFieldIDTeacher.getText());
            
            JOptionPane.showMessageDialog(null, "Assign successfully!");
        } catch (NamingException | ParseException e) {
            Logger.getLogger(EditRoomReg.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jButtonResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetMouseEntered
        setColor(jButtonReset);
    }//GEN-LAST:event_jButtonResetMouseEntered

    private void jButtonResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetMouseExited
        resetColor(jButtonReset);
    }//GEN-LAST:event_jButtonResetMouseExited

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jTextFieldIDTeacher.setText("");
        jTextFieldNameTeacher.setText("");
        jTextFieldNameCourse.setText("");
        jTextFieldIDCourse.setText("");
        jTextFieldType.setText("");
        jTextFieldBirthday.setText("");
        
        jComboBoxRoom.removeAllItems();
        jComboBoxRoom.addItem("");
        jComboBoxRoom.setSelectedIndex(0);
        
        jTextFieldSession.setText("");
        jTextFieldBirthday.setText("");
        
        jTextFieldIDTeacher.requestFocus();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonLoadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoadMouseEntered
        setColor(jButtonLoad);
    }//GEN-LAST:event_jButtonLoadMouseEntered

    private void jButtonLoadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoadMouseExited
        resetColor(jButtonLoad);
    }//GEN-LAST:event_jButtonLoadMouseExited

    private void jButtonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadActionPerformed
        try {
            SystemStudentManagementRemote session = (SystemStudentManagementRemote) init.getCtx().lookup(init.getJNDI());
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
            Object[] roomInfo = session.getRoomByID(jComboBoxRoom.getSelectedItem().toString());
            jTextFieldIDCourse.setText(roomInfo[1].toString());
            jTextFieldIDTeacher.setText(roomInfo[2].toString());
            jTextFieldStartDate.setText(formatter.format((Date)roomInfo[3]));
            jTextFieldSession.setText(roomInfo[4].toString());
        } catch (NamingException ex) {
            Logger.getLogger(EditRoomReg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLoadActionPerformed

    public void setColor(javax.swing.JButton button) {
        button.setBackground(new java.awt.Color(115, 163, 239));
    }

    public void resetColor(javax.swing.JButton button) {
        button.setBackground(new java.awt.Color(12, 91, 160));
    }
    
    public boolean checkValid(int day, int month, int year) {
        if (isLeapYear(year)) {
            if (month == 2 && day > 29) {
                return false;
            }
        } else {
            if (month == 2 && day > 28) {
                return false;
            }
        }
        return true;
    }

    private boolean isLeapYear(int year) {
        return year % 400 == 0 || (year % 4 == 0 && year % 100 != 0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelBirthday;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonLoad;
    private javax.swing.JButton jButtonLoadData1;
    private javax.swing.JButton jButtonLoadData2;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<String> jComboBoxRoom;
    private javax.swing.JTable jDataTable;
    private javax.swing.JTable jDataTable1;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelIDCourse;
    private javax.swing.JLabel jLabelIDRoom;
    private javax.swing.JLabel jLabelIDTeacher;
    private javax.swing.JLabel jLabelNameCourse;
    private javax.swing.JLabel jLabelNameTeacher;
    private javax.swing.JLabel jLabelSession;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldBirthday;
    private javax.swing.JTextField jTextFieldIDCourse;
    private javax.swing.JTextField jTextFieldIDTeacher;
    private javax.swing.JTextField jTextFieldNameCourse;
    private javax.swing.JTextField jTextFieldNameTeacher;
    private javax.swing.JTextField jTextFieldSession;
    private javax.swing.JTextField jTextFieldStartDate;
    private javax.swing.JTextField jTextFieldType;
    // End of variables declaration//GEN-END:variables
}
