/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.admin;

import control.InitialStatelessStudentOrAdmin;
import edu.tdt.entity.Student;
import edu.tdt.service.SystemStudentManagementRemote;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HAU
 */
public class EditStdReg extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditStdReg
     */
    
    InitialStatelessStudentOrAdmin init;
    DefaultTableModel dftable;
    static int countStudent;
    public EditStdReg() {
        initComponents();
        init = new InitialStatelessStudentOrAdmin();
        dftable = (DefaultTableModel) jDataTable.getModel();
        countStudent = 0;
        loadDataOnJTable();
    }
    
    private void loadDataOnJTable() {
        try {            
            dftable.setRowCount(0);
            SimpleDateFormat formatter1 = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat formatter2 = new SimpleDateFormat("yyyy-MM-dd");

            SystemStudentManagementRemote session = (SystemStudentManagementRemote) init.getCtx().lookup(init.getJNDI());
            List<Object[]> students = session.getAllStudents();
            countStudent = students.size();
            for(int i = 0 ; i < students.size() ; i++){
                String id_student = students.get(i)[0].toString();
                String first_name = students.get(i)[1].toString();
                String last_name = students.get(i)[2].toString();
                String student_birthday = formatter1.format(formatter2.parse(students.get(i)[3].toString()));
                String gender = ("true".equals(students.get(i)[4].toString()))?"Male":"Female";
                String email = students.get(i)[5].toString();
                String phone = students.get(i)[6].toString();
                String address = students.get(i)[7].toString();
                String admission = formatter1.format(formatter2.parse(students.get(i)[8].toString()));
                String username = students.get(i)[9].toString();
                String status = students.get(i)[10].toString();
                

                Object[] ojb = {id_student, first_name, last_name, student_birthday, gender, email, phone, address, admission, username, status};
                dftable.addRow(ojb);
            }
            jTextField1.setText(String.valueOf(countStudent));
        } catch (NamingException | ParseException ex) {
            Logger.getLogger(EditStdReg.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelFirstName = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabelLastName = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabelBirthday = new javax.swing.JLabel();
        jComboBoxDay1 = new javax.swing.JComboBox<>();
        jComboBoxMonth1 = new javax.swing.JComboBox<>();
        jComboBoxYear1 = new javax.swing.JComboBox<>();
        jLabelGender = new javax.swing.JLabel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelPhone = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabelAddress = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabelAdmission = new javax.swing.JLabel();
        jComboBoxDay2 = new javax.swing.JComboBox<>();
        jComboBoxMonth2 = new javax.swing.JComboBox<>();
        jComboBoxYear2 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabelStatus = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDataTable = new javax.swing.JTable();
        jButtonFind = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jTextFieldIDStudent = new javax.swing.JTextField();
        jButtonLoadData = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabelSutdents = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Edit Student");
        setPreferredSize(new java.awt.Dimension(1920, 977));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 51, 204));
        jLabelTitle.setText("UPDATE STUDENT INFORMATION");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 402));

        jLabelID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelID.setText("ID Student");

        jTextFieldID.setEditable(false);
        jTextFieldID.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelFirstName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelFirstName.setText("First Name");

        jTextFieldFirstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelLastName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelLastName.setText("Last Name");

        jTextFieldLastName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelBirthday.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelBirthday.setText("Birthday");

        jComboBoxDay1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxDay1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day" }));

        jComboBoxMonth1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxMonth1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month" }));

        jComboBoxYear1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxYear1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year" }));

        jLabelGender.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelGender.setText("Gender");

        jRadioButtonMale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButtonMale.setSelected(true);
        jRadioButtonMale.setText("Male");

        jRadioButtonFemale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButtonFemale.setText("Female");

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelEmail.setText("Email");

        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelPhone.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelPhone.setText("Phone");

        jTextFieldPhone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelAddress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelAddress.setText("Address");

        jTextFieldAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelAdmission.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelAdmission.setText("Admission");

        jComboBoxDay2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxDay2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day" }));

        jComboBoxMonth2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxMonth2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", " " }));

        jComboBoxYear2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxYear2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year" }));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabelStatus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelStatus.setText("Status");

        jTextFieldStatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(318, 318, 318)
                                .addComponent(jComboBoxDay1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelGender)
                                            .addComponent(jComboBoxMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addComponent(jComboBoxYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelBirthday)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(404, 404, 404)
                                .addComponent(jLabelLastName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(403, 403, 403)
                                .addComponent(jLabelFirstName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 261, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonMale)
                                        .addGap(82, 82, 82)
                                        .addComponent(jRadioButtonFemale)
                                        .addGap(361, 361, 361))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(269, 269, 269)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelID)
                                .addGap(402, 402, 402)))))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(253, 253, 253))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelAddress)
                                    .addGap(396, 396, 396)))
                            .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelEmail)
                                .addGap(417, 417, 417))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelPhone)
                                .addGap(411, 411, 411))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelAdmission)
                                .addGap(383, 383, 383))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jComboBoxDay2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStatus)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jComboBoxYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(jLabelID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFirstName)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabelLastName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBirthday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonFemale)
                            .addComponent(jRadioButtonMale))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAdmission)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jDataTable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Birthday", "Gender", "Email", "Phone", "Address", "Admission", "Username", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jDataTable.setRowHeight(30);
        jDataTable.setRowMargin(2);
        jDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jDataTable);

        jButtonFind.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonFind.setText("Find");
        jButtonFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(12, 91, 160));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseExited(evt);
            }
        });
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonClose.setBackground(new java.awt.Color(12, 91, 160));
        jButtonClose.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonClose.setText("Close");
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCloseMouseExited(evt);
            }
        });
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonReset.setBackground(new java.awt.Color(12, 91, 160));
        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonResetMouseExited(evt);
            }
        });
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jTextFieldIDStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jButtonLoadData.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonLoadData.setText("ListAll");
        jButtonLoadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadDataActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelSutdents.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelSutdents.setText("Students");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1899, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(609, 609, 609)
                            .addComponent(jLabelTitle))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(772, 772, 772)
                            .addComponent(jTextFieldIDStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonFind)
                            .addGap(12, 12, 12)
                            .addComponent(jButtonLoadData))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(800, 800, 800)
                            .addComponent(jButtonUpdate)
                            .addGap(31, 31, 31)
                            .addComponent(jButtonReset)
                            .addGap(30, 30, 30)
                            .addComponent(jButtonClose)
                            .addGap(602, 602, 602)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)
                            .addComponent(jLabelSutdents))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1899, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIDStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFind)
                    .addComponent(jButtonLoadData))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonUpdate)
                                .addComponent(jButtonReset)
                                .addComponent(jButtonClose))
                            .addComponent(jLabelSutdents, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindActionPerformed
        try {            
            dftable.setRowCount(0);
            SimpleDateFormat formatter1 = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat formatter2 = new SimpleDateFormat("yyyy-MM-dd");

            SystemStudentManagementRemote session = (SystemStudentManagementRemote) init.getCtx().lookup(init.getJNDI());
            List<Object[]> students = session.getAllStudents(jTextFieldIDStudent.getText().substring(0, 1).toUpperCase() + jTextFieldIDStudent.getText().substring(1));
            countStudent = students.size();
            for(int i = 0 ; i < students.size() ; i++){
                String id_student = students.get(i)[0].toString();
                String first_name = students.get(i)[1].toString();
                String last_name = students.get(i)[2].toString();
                String student_birthday = formatter1.format(formatter2.parse(students.get(i)[3].toString()));
                String gender = ("true".equals(students.get(i)[4].toString()))?"Male":"Female";
                String email = students.get(i)[5].toString();
                String phone = students.get(i)[6].toString();
                String address = students.get(i)[7].toString();
                String admission = formatter1.format(formatter2.parse(students.get(i)[8].toString()));
                String username = students.get(i)[9].toString();
                String status = students.get(i)[10].toString();
                

                Object[] ojb = {id_student, first_name, last_name, student_birthday, gender, email, phone, address, admission, username, status};
                dftable.addRow(ojb);
            }
        } catch (NamingException | ParseException ex) {
            Logger.getLogger(EditStdReg.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonFindActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        try {
            SystemStudentManagementRemote session = (SystemStudentManagementRemote) init.getCtx().lookup(init.getJNDI());
            
            
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
            Random rd = new Random();

            //Get first name
            String first_name = jTextFieldFirstName.getText();
            if ("".equals(first_name)) {
                jTextFieldFirstName.requestFocus();
                return;
            }

            //Get last name
            String last_name = jTextFieldLastName.getText();
            if ("".equals(last_name)) {
                jTextFieldLastName.requestFocus();
                return;
            }

            //Get birth or admission from combobox
            Date birth;
            Date admission;

            String day1 = jComboBoxDay1.getSelectedItem().toString();
            if (day1.equals("Day")) {
                jComboBoxDay1.requestFocus();
                return;
            }

            String day2 = jComboBoxDay2.getSelectedItem().toString();
            if (day2.equals("Day")) {
                jComboBoxDay2.requestFocus();
                return;
            }

            String month1 = jComboBoxMonth1.getSelectedItem().toString();
            if (month1.equals("Month")) {
                jComboBoxMonth1.requestFocus();
                return;
            }
            
            String month2 = jComboBoxMonth2.getSelectedItem().toString();
            if (month2.equals("Month")) {
                jComboBoxMonth2.requestFocus();
                return;
            }

            String year1 = jComboBoxYear1.getSelectedItem().toString();
            if (year1.equals("Year")) {
                jComboBoxYear1.requestFocus();
                return;
            }
            
            String year2 = jComboBoxYear2.getSelectedItem().toString();
            if (year2.equals("Year")) {
                jComboBoxYear2.requestFocus();
                return;
            }

            String stringBirth = day1 + "-" + month1 + "-" + year1;
            String stringAdmission = day2 + "-" + month2 + "-" + year2;
            //Check stringBirth is valid or not 
            if (checkValid(Integer.parseInt(day1), Integer.parseInt(month1), Integer.parseInt(year1)) && checkValid(Integer.parseInt(day2), Integer.parseInt(month2), Integer.parseInt(year2))) {
                birth = formatter.parse(stringBirth);
                admission = formatter.parse(stringAdmission);
            } else {
                JOptionPane.showMessageDialog(null, "Date is not valid!!!");
                return;
            }
            
            boolean gender = (jRadioButtonMale.isSelected() == true);

            String email = jTextFieldEmail.getText();
            if (email.equals("")) {
                jTextFieldEmail.requestFocus();
                return;
            }
            
            String phone = jTextFieldPhone.getText();
            if ("".equals(phone)) {
                jTextFieldPhone.requestFocus();
                return;
            }
            
            String address = jTextFieldAddress.getText();
            if (address.equals("")) {
                jTextFieldAddress.requestFocus();
                return;
            }

            Student student = new Student();
            String id_student = jTextFieldID.getText();        
            String status = jTextFieldStatus.getText();
            
            //Create student and add into database
            student.setIdStudent(id_student);
            student.setFirstname(first_name);
            student.setLastname(last_name);
            student.setGender(gender);
            student.setBirthday(birth);
            student.setEmail(email);
            student.setPhone(phone);
            student.setAddress(address);
            student.setAdmission(admission);
            student.setStatus(status);

            session.updateStudent(student);
            
            JOptionPane.showMessageDialog(null, "Edit successfully!!!");
        } catch (NamingException | ParseException e) {
            Logger.getLogger(EditStdReg.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDataTableMouseClicked
        int selectedIndexRow = jDataTable.getSelectedRow();
        
        jTextFieldID.setText(dftable.getValueAt(selectedIndexRow, 0).toString());
        jTextFieldFirstName.setText(dftable.getValueAt(selectedIndexRow, 1).toString());
        jTextFieldLastName.setText(dftable.getValueAt(selectedIndexRow, 2).toString());
        String birthday = dftable.getValueAt(selectedIndexRow, 3).toString();
        String[] obj = birthday.split("/");
        jComboBoxDay1.removeAllItems();
        jComboBoxDay1.addItem(obj[0]);
        jComboBoxDay1.setSelectedIndex(0);
        jComboBoxMonth1.removeAllItems();
        jComboBoxMonth1.addItem(obj[1]);
        jComboBoxMonth1.setSelectedIndex(0);
        jComboBoxYear1.removeAllItems();
        jComboBoxYear1.addItem(obj[2]);
        jComboBoxYear1.setSelectedIndex(0);  
        jRadioButtonMale.setSelected(dftable.getValueAt(selectedIndexRow, 4).equals("Male"));
        jRadioButtonFemale.setSelected(dftable.getValueAt(selectedIndexRow, 4).equals("Female"));
        jTextFieldEmail.setText(dftable.getValueAt(selectedIndexRow, 5).toString());
        jTextFieldPhone.setText(dftable.getValueAt(selectedIndexRow, 6).toString());
        jTextFieldAddress.setText(dftable.getValueAt(selectedIndexRow, 7).toString());
        String admission = dftable.getValueAt(selectedIndexRow, 8).toString();
        obj = admission.split("/");
        jComboBoxDay2.removeAllItems();
        jComboBoxDay2.addItem(obj[0]);
        jComboBoxDay2.setSelectedIndex(0);
        jComboBoxMonth2.removeAllItems();
        jComboBoxMonth2.addItem(obj[1]);
        jComboBoxMonth2.setSelectedIndex(0);
        jComboBoxYear2.removeAllItems();
        jComboBoxYear2.addItem(obj[2]);
        jComboBoxYear2.setSelectedIndex(0);
        
        jTextFieldStatus.setText(dftable.getValueAt(selectedIndexRow, 10).toString());
    }//GEN-LAST:event_jDataTableMouseClicked

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jTextFieldID.setText("");
        jTextFieldFirstName.setText("");
        jTextFieldLastName.setText("");
        
        jComboBoxDay1.removeAllItems();
        jComboBoxDay1.addItem("Day");
        jComboBoxDay1.setSelectedIndex(0);
        
        jComboBoxMonth1.removeAllItems();
        jComboBoxMonth1.addItem("Month");
        jComboBoxMonth1.setSelectedIndex(0);
        
        jComboBoxYear1.removeAllItems();
        jComboBoxYear1.addItem("Year");
        jComboBoxYear1.setSelectedIndex(0);
        
        jRadioButtonMale.setSelected(true);

        jTextFieldEmail.setText("");
        jTextFieldPhone.setText("");
        jTextFieldAddress.setText("");

        jComboBoxDay2.removeAllItems();
        jComboBoxDay2.addItem("Day");
        jComboBoxDay2.setSelectedIndex(0);
        
        jComboBoxMonth2.removeAllItems();
        jComboBoxMonth2.addItem("Month");
        jComboBoxMonth2.setSelectedIndex(0);
        
        jComboBoxYear2.removeAllItems();
        jComboBoxYear2.addItem("Year");
        jComboBoxYear2.setSelectedIndex(0);
        
        jTextFieldStatus.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseEntered
        setColor(jButtonUpdate);
    }//GEN-LAST:event_jButtonUpdateMouseEntered

    private void jButtonUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseExited
        resetColor(jButtonUpdate);
    }//GEN-LAST:event_jButtonUpdateMouseExited

    private void jButtonResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetMouseEntered
        setColor(jButtonReset);
    }//GEN-LAST:event_jButtonResetMouseEntered

    private void jButtonResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetMouseExited
        resetColor(jButtonReset);
    }//GEN-LAST:event_jButtonResetMouseExited

    private void jButtonCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseEntered
        setColor(jButtonClose);
    }//GEN-LAST:event_jButtonCloseMouseEntered

    private void jButtonCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMouseExited
        resetColor(jButtonClose);
    }//GEN-LAST:event_jButtonCloseMouseExited

    private void jButtonLoadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadDataActionPerformed
        loadDataOnJTable();
    }//GEN-LAST:event_jButtonLoadDataActionPerformed

    
    public void setColor(javax.swing.JButton button) {
        button.setBackground(new java.awt.Color(115, 163, 239));
    }

    public void resetColor(javax.swing.JButton button) {
        button.setBackground(new java.awt.Color(12, 91, 160));
    }
    
    public boolean checkValid(int day, int month, int year) {
        if (isLeapYear(year)) {
            if (month == 2 && day > 29) {
                return false;
            }
        } else {
            if (month == 2 && day > 28) {
                return false;
            }
        }
        return true;
    }

    private boolean isLeapYear(int year) {
        return year % 400 == 0 || (year % 4 == 0 && year % 100 != 0);
    }
    
    public int getCountStudents(){
        return countStudent;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonFind;
    private javax.swing.JButton jButtonLoadData;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxDay1;
    private javax.swing.JComboBox<String> jComboBoxDay2;
    private javax.swing.JComboBox<String> jComboBoxMonth1;
    private javax.swing.JComboBox<String> jComboBoxMonth2;
    private javax.swing.JComboBox<String> jComboBoxYear1;
    private javax.swing.JComboBox<String> jComboBoxYear2;
    private javax.swing.JTable jDataTable;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelAdmission;
    private javax.swing.JLabel jLabelBirthday;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelSutdents;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldIDStudent;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldStatus;
    // End of variables declaration//GEN-END:variables
}
