/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.admin;

import control.InitialStatelessStudentOrAdmin;
import edu.tdt.service.SystemStudentManagementRemote;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import views.login.Login;

/**
 *
 * @author HAU
 */
public class EditRequest extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditRequest
     */
    Login x;
    InitialStatelessStudentOrAdmin init;
    DefaultTableModel dftable;

    public EditRequest() {
        initComponents();
        x = new Login();
        init = new InitialStatelessStudentOrAdmin();
        dftable = (DefaultTableModel) jDataTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDataTable = new javax.swing.JTable();
        jButtonUpdate = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelIDRequest = new javax.swing.JLabel();
        jTextFieldIDRequest = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();
        jButtonLoad = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Edit Request");
        setPreferredSize(new java.awt.Dimension(1920, 951));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 51, 204));
        jLabelTitle.setText("EDIT THE REQUESTS");

        jDataTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Parent Name", "Email", "Birthday", "Address", "Phone", "Course", "Information", "Datecreated", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jDataTable.setRowHeight(30);
        jDataTable.setRowMargin(2);
        jDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jDataTable);

        jButtonUpdate.setBackground(new java.awt.Color(12, 91, 160));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonUpdateMouseExited(evt);
            }
        });
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonReset.setBackground(new java.awt.Color(12, 91, 160));
        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonResetMouseExited(evt);
            }
        });
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelIDRequest.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelIDRequest.setText("ID Request");

        jTextFieldIDRequest.setEditable(false);
        jTextFieldIDRequest.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIDRequest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelStatus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelStatus.setText("Status");

        jTextFieldStatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldIDRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(177, 177, 177))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelIDRequest)
                                .addGap(299, 299, 299))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelStatus)
                        .addGap(338, 338, 338))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIDRequest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldIDRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonLoad.setBackground(new java.awt.Color(12, 91, 160));
        jButtonLoad.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonLoad.setText("Load");
        jButtonLoad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoadMouseExited(evt);
            }
        });
        jButtonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 638, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonUpdate)
                                .addGap(79, 79, 79)
                                .addComponent(jButtonReset)
                                .addGap(773, 773, 773))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(679, 679, 679))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(522, 522, 522))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLoad)
                .addGap(593, 593, 593))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addGap(25, 25, 25)
                .addComponent(jButtonLoad)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonUpdate))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseEntered
        setColor(jButtonUpdate);
    }//GEN-LAST:event_jButtonUpdateMouseEntered

    private void jButtonUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUpdateMouseExited
        resetColor(jButtonUpdate);
    }//GEN-LAST:event_jButtonUpdateMouseExited

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        try {
            SystemStudentManagementRemote session = (SystemStudentManagementRemote) init.getCtx().lookup(init.getJNDI());
            session.updateRequest(jTextFieldStatus.getText(), jTextFieldIDRequest.getText());
            JOptionPane.showMessageDialog(null, "Update Successfully!");
            
        } catch (NamingException ex) {
            Logger.getLogger(EditRequest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetMouseEntered
        setColor(jButtonReset);
    }//GEN-LAST:event_jButtonResetMouseEntered

    private void jButtonResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetMouseExited
        resetColor(jButtonReset);
    }//GEN-LAST:event_jButtonResetMouseExited

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jTextFieldIDRequest.setText("");
        jTextFieldStatus.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonLoadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoadMouseEntered
        setColor(jButtonLoad);
    }//GEN-LAST:event_jButtonLoadMouseEntered

    private void jButtonLoadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoadMouseExited
        resetColor(jButtonLoad);
    }//GEN-LAST:event_jButtonLoadMouseExited

    private void jButtonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadActionPerformed
        try {
            dftable.setRowCount(0);
            SimpleDateFormat formatter1 = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat formatter2 = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

            SystemStudentManagementRemote session = (SystemStudentManagementRemote) init.getCtx().lookup(init.getJNDI());
            List<Object[]> listRequests = session.getAllRequests(x.getUserID());
            
            for (int i = 0; i < listRequests.size(); i++) {
                String id = listRequests.get(i)[0].toString();
                String name = listRequests.get(i)[1].toString();
                String parentname = listRequests.get(i)[2].toString();
                String email = listRequests.get(i)[3].toString();
                String birthday = formatter1.format(formatter2.parse(listRequests.get(i)[4].toString()));
                String address = listRequests.get(i)[5].toString();
                String phone = listRequests.get(i)[6].toString();
                String course = listRequests.get(i)[7].toString();
                String info = listRequests.get(i)[8].toString();
                String datecreated = sdf.format(sdf.parse(listRequests.get(i)[9].toString()));
                String status = listRequests.get(i)[10].toString();
                
                Object[] ojb = {id, name, parentname, email, birthday, address, phone, course, info, datecreated, status};
                dftable.addRow(ojb);
            }
        } catch (NamingException | ParseException ex) {
            Logger.getLogger(EditRequest.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLoadActionPerformed

    private void jDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDataTableMouseClicked
        int selectedIndexRow = jDataTable.getSelectedRow();
        
        jTextFieldIDRequest.setText(dftable.getValueAt(selectedIndexRow, 0).toString());
        jTextFieldStatus.setText(dftable.getValueAt(selectedIndexRow, 10).toString());
    }//GEN-LAST:event_jDataTableMouseClicked

    public void setColor(javax.swing.JButton button) {
        button.setBackground(new java.awt.Color(115, 163, 239));
    }

    public void resetColor(javax.swing.JButton button) {
        button.setBackground(new java.awt.Color(12, 91, 160));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoad;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JTable jDataTable;
    private javax.swing.JLabel jLabelIDRequest;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldIDRequest;
    private javax.swing.JTextField jTextFieldStatus;
    // End of variables declaration//GEN-END:variables
}
