/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.admin;

import control.InitialStatelessStudentOrAdmin;
import edu.tdt.service.SystemStudentManagementRemote;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HAU
 */
public class RegisterCourse extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegisterCourse
     */
    InitialStatelessStudentOrAdmin init;
    DefaultTableModel dftable1;
    DefaultTableModel dftable2;

    public RegisterCourse() {
        initComponents();
        init = new InitialStatelessStudentOrAdmin();
        dftable1 = (DefaultTableModel) jDataTable.getModel();
        dftable2 = (DefaultTableModel) jDataTable1.getModel();
    }

    private void loadCoursesOnJTable() {
        try {
            dftable1.setRowCount(0);

            SystemStudentManagementRemote session = (SystemStudentManagementRemote) init.getCtx().lookup(init.getJNDI());
            List<Object[]> courses = session.getCourses();

            for (int i = 0; i < courses.size(); i++) {
                String id_course = courses.get(i)[0].toString();
                String name = courses.get(i)[1].toString();
                String duration = courses.get(i)[2].toString();
                String fee = courses.get(i)[3].toString();
                String type = courses.get(i)[4].toString();

                Object[] ojb = {id_course, name, duration, fee, type};
                dftable1.addRow(ojb);
            }
        } catch (NamingException ex) {
            Logger.getLogger(EditCourseReg.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadStudentsOnJTable() {
        try {
            dftable2.setRowCount(0);
            SimpleDateFormat formatter1 = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat formatter2 = new SimpleDateFormat("yyyy-MM-dd");

            SystemStudentManagementRemote session = (SystemStudentManagementRemote) init.getCtx().lookup(init.getJNDI());
            List<Object[]> students = session.getAllStudents();

            for (int i = 0; i < students.size(); i++) {
                String id_student = students.get(i)[0].toString();
                String fullname = students.get(i)[2].toString() + " " + students.get(i)[1].toString();
                String student_birthday = formatter1.format(formatter2.parse(students.get(i)[3].toString()));
                String gender = ("true".equals(students.get(i)[4].toString())) ? "Male" : "Female";
                String email = students.get(i)[5].toString();

                Object[] ojb = {id_student, fullname, student_birthday, gender, email};
                dftable2.addRow(ojb);
            }
        } catch (NamingException | ParseException ex) {
            Logger.getLogger(EditStdReg.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLoadData2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDataTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDataTable1 = new javax.swing.JTable();
        jLabelTitle = new javax.swing.JLabel();
        jPanel = new javax.swing.JPanel();
        jLabelIDCourse = new javax.swing.JLabel();
        jTextFieldIDCourse = new javax.swing.JTextField();
        jLabelNameCourse = new javax.swing.JLabel();
        jTextFieldNameCourse = new javax.swing.JTextField();
        jLabelType = new javax.swing.JLabel();
        jTextFieldType = new javax.swing.JTextField();
        jLabelIDStudent = new javax.swing.JLabel();
        jTextFieldIDStudent = new javax.swing.JTextField();
        jLabelNameStudent = new javax.swing.JLabel();
        jTextFieldNameStudent = new javax.swing.JTextField();
        JLabelBirthday = new javax.swing.JLabel();
        jTextFieldBirthday = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jButtonLoadData1 = new javax.swing.JButton();
        jButtonAssign = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Assign Course");

        jButtonLoadData2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonLoadData2.setText("Load");
        jButtonLoadData2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoadData2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoadData2MouseExited(evt);
            }
        });
        jButtonLoadData2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadData2ActionPerformed(evt);
            }
        });

        jDataTable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Duration", "Fee", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jDataTable.setRowHeight(30);
        jDataTable.setRowMargin(2);
        jDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jDataTable);

        jDataTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jDataTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Full Name", "Birthday", "Gender", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jDataTable1.setRowHeight(30);
        jDataTable1.setRowMargin(2);
        jDataTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDataTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jDataTable1);

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 51, 204));
        jLabelTitle.setText("REGISTER COURSE FOR STUDENT");

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setPreferredSize(new java.awt.Dimension(1920, 402));

        jLabelIDCourse.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelIDCourse.setText("ID Course");

        jTextFieldIDCourse.setEditable(false);
        jTextFieldIDCourse.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIDCourse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelNameCourse.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelNameCourse.setText("Name");

        jTextFieldNameCourse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelType.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelType.setText("Type");

        jTextFieldType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelIDStudent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelIDStudent.setText("ID Student");

        jTextFieldIDStudent.setEditable(false);
        jTextFieldIDStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabelNameStudent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelNameStudent.setText("Full Name");

        jTextFieldNameStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        JLabelBirthday.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLabelBirthday.setText("Birthday");

        jTextFieldBirthday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabelIDCourse))
                    .addComponent(jTextFieldIDCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabelNameCourse))
                    .addComponent(jTextFieldNameCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(308, 308, 308)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIDStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addComponent(jLabelIDStudent)
                                .addGap(123, 123, 123))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addComponent(jLabelNameStudent)
                                .addGap(128, 128, 128))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addComponent(JLabelBirthday)
                                .addGap(136, 136, 136)))))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelIDCourse)
                .addGap(11, 11, 11)
                .addComponent(jTextFieldIDCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabelNameCourse)
                .addGap(11, 11, 11)
                .addComponent(jTextFieldNameCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabelType)
                .addGap(21, 21, 21)
                .addComponent(jTextFieldType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelIDStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldIDStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabelNameStudent)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(JLabelBirthday)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButtonLoadData1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonLoadData1.setText("Load");
        jButtonLoadData1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoadData1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoadData1MouseExited(evt);
            }
        });
        jButtonLoadData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadData1ActionPerformed(evt);
            }
        });

        jButtonAssign.setBackground(new java.awt.Color(12, 91, 160));
        jButtonAssign.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonAssign.setText("Assign");
        jButtonAssign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAssignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAssignMouseExited(evt);
            }
        });
        jButtonAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAssignActionPerformed(evt);
            }
        });

        jButtonReset.setBackground(new java.awt.Color(12, 91, 160));
        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonResetMouseExited(evt);
            }
        });
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addGap(617, 617, 617))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jButtonLoadData1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLoadData2)
                .addGap(221, 221, 221))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1877, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(849, 849, 849)
                        .addComponent(jButtonAssign)
                        .addGap(66, 66, 66)
                        .addComponent(jButtonReset)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitle)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLoadData2)
                    .addComponent(jButtonLoadData1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAssign)
                    .addComponent(jButtonReset))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDataTableMouseClicked
        int selectedIndexRow = jDataTable.getSelectedRow();

        jTextFieldIDCourse.setText(dftable1.getValueAt(selectedIndexRow, 0).toString());
        jTextFieldNameCourse.setText(dftable1.getValueAt(selectedIndexRow, 1).toString());
        jTextFieldType.setText(dftable1.getValueAt(selectedIndexRow, 2).toString());
    }//GEN-LAST:event_jDataTableMouseClicked

    private void jDataTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDataTable1MouseClicked
        int selectedIndexRow = jDataTable1.getSelectedRow();

        jTextFieldIDStudent.setText(dftable2.getValueAt(selectedIndexRow, 0).toString());
        jTextFieldNameStudent.setText(dftable2.getValueAt(selectedIndexRow, 1).toString());
        jTextFieldBirthday.setText(dftable2.getValueAt(selectedIndexRow, 2).toString());

    }//GEN-LAST:event_jDataTable1MouseClicked

    private void jButtonLoadData2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadData2ActionPerformed
        loadStudentsOnJTable();
    }//GEN-LAST:event_jButtonLoadData2ActionPerformed

    private void jButtonLoadData2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoadData2MouseEntered
        setColor(jButtonLoadData2);
    }//GEN-LAST:event_jButtonLoadData2MouseEntered

    private void jButtonLoadData2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoadData2MouseExited
        resetColor(jButtonLoadData2);
    }//GEN-LAST:event_jButtonLoadData2MouseExited

    private void jButtonLoadData1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoadData1MouseEntered
        setColor(jButtonLoadData1);
    }//GEN-LAST:event_jButtonLoadData1MouseEntered

    private void jButtonLoadData1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoadData1MouseExited
        resetColor(jButtonLoadData1);
    }//GEN-LAST:event_jButtonLoadData1MouseExited

    private void jButtonLoadData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadData1ActionPerformed
        loadCoursesOnJTable();
    }//GEN-LAST:event_jButtonLoadData1ActionPerformed

    private void jButtonAssignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssignMouseEntered
        setColor(jButtonAssign);
    }//GEN-LAST:event_jButtonAssignMouseEntered

    private void jButtonAssignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssignMouseExited
        resetColor(jButtonAssign);
    }//GEN-LAST:event_jButtonAssignMouseExited

    private void jButtonAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAssignActionPerformed
        try {
            SystemStudentManagementRemote session = (SystemStudentManagementRemote) init.getCtx().lookup(init.getJNDI());
            session.assignCourseForStudent(jTextFieldIDStudent.getText(), jTextFieldIDCourse.getText());
            JOptionPane.showMessageDialog(null, "Assign successfully!");
        } catch (NamingException e) {
            Logger.getLogger(EditMark.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButtonAssignActionPerformed

    private void jButtonResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetMouseEntered
        setColor(jButtonReset);
    }//GEN-LAST:event_jButtonResetMouseEntered

    private void jButtonResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetMouseExited
        resetColor(jButtonReset);
    }//GEN-LAST:event_jButtonResetMouseExited

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jTextFieldIDStudent.setText("");
        jTextFieldNameStudent.setText("");
        jTextFieldNameCourse.setText("");
        jTextFieldIDCourse.setText("");
        jTextFieldType.setText("");
        jTextFieldBirthday.setText("");    
        
        jTextFieldIDStudent.requestFocus();
    }//GEN-LAST:event_jButtonResetActionPerformed

    public void setColor(javax.swing.JButton button) {
        button.setBackground(new java.awt.Color(115, 163, 239));
    }

    public void resetColor(javax.swing.JButton button) {
        button.setBackground(new java.awt.Color(12, 91, 160));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelBirthday;
    private javax.swing.JButton jButtonAssign;
    private javax.swing.JButton jButtonLoadData1;
    private javax.swing.JButton jButtonLoadData2;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JTable jDataTable;
    private javax.swing.JTable jDataTable1;
    private javax.swing.JLabel jLabelIDCourse;
    private javax.swing.JLabel jLabelIDStudent;
    private javax.swing.JLabel jLabelNameCourse;
    private javax.swing.JLabel jLabelNameStudent;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldBirthday;
    private javax.swing.JTextField jTextFieldIDCourse;
    private javax.swing.JTextField jTextFieldIDStudent;
    private javax.swing.JTextField jTextFieldNameCourse;
    private javax.swing.JTextField jTextFieldNameStudent;
    private javax.swing.JTextField jTextFieldType;
    // End of variables declaration//GEN-END:variables
}
