/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.admin;

import control.InitialStatelessStudentOrAdmin;
import edu.tdt.service.SystemStudentManagementRemote;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HAU
 */
public class ViewCoursesRegistered extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditStdReg
     */
    InitialStatelessStudentOrAdmin init;
    DefaultTableModel dftable;
    ArrayList<String> listCoursesRegistered;
    static int countCourses;

    public ViewCoursesRegistered() {
        initComponents();
        init = new InitialStatelessStudentOrAdmin();
        dftable = (DefaultTableModel) jDataTable.getModel();
        countCourses = 0;
        loadDataOnJTable();
    }

    private void loadDataOnJTable() {
        try {
            dftable.setRowCount(0);

            SystemStudentManagementRemote session = (SystemStudentManagementRemote) init.getCtx().lookup(init.getJNDI());
            listCoursesRegistered = session.getListCoursesRegistered();
            SimpleDateFormat formatter1 = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat formatter2 = new SimpleDateFormat("yyyy-MM-dd");

            ArrayList<String> idCourses = new ArrayList<>();
            for (int i = 0; i < listCoursesRegistered.size(); i++) {
                String[] obj = listCoursesRegistered.get(i).split(";");
                String id_student = obj[0];
                String student_name = obj[1] + " " + obj[2];
                String student_birthday = formatter1.format(formatter2.parse(obj[3]));
                String gender = ("true".equals(obj[4])) ? "Male" : "Female";

                //Count number of courses have registered
                String id_course = obj[5];
                if (!idCourses.contains(id_course)) {
                    idCourses.add(id_course);
                    jComboBoxIDCourse.addItem(id_course);
                }

                String course_name = obj[6];
                String type = obj[7];
                switch (type) {
                    case "KG":
                        type = "Kindergarten";
                        break;
                    case "KD":
                        type = "Kid";
                        break;
                    case "YT":
                        type = "Youth";
                        break;
                    case "ADU":
                        type = "Adult";
                        break;
                }

                Object[] ojb = {id_student, student_name, student_birthday, gender, id_course, course_name, type};
                dftable.addRow(ojb);
            }

            jTextFieldCount.setText(String.valueOf(idCourses.size()));
        } catch (NamingException | ParseException ex) {
            Logger.getLogger(ViewCoursesRegistered.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        jTextFieldCount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDataTable = new javax.swing.JTable();
        jButtonFind = new javax.swing.JButton();
        jComboBoxIDCourse = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("View Courses Registered");

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(0, 51, 204));
        jLabelTitle.setText("VIEW COURSES REGISTERED");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 402));

        jLabelID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelID.setText("Courses have registered");

        jTextFieldCount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(jLabelID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(465, 465, 465)
                        .addComponent(jTextFieldCount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(613, 613, 613))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelID)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldCount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDataTable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Student", "Name Student", "Birthday", "Gender", "ID Course", "Name Course", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jDataTable.setRowHeight(30);
        jDataTable.setRowMargin(2);
        jScrollPane1.setViewportView(jDataTable);

        jButtonFind.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonFind.setText("Find");
        jButtonFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindActionPerformed(evt);
            }
        });

        jComboBoxIDCourse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxIDCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1092, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addGap(275, 275, 275))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxIDCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFind)
                        .addGap(381, 381, 381)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxIDCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFind))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindActionPerformed
        try {
            dftable.setRowCount(0);

            SimpleDateFormat formatter1 = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat formatter2 = new SimpleDateFormat("yyyy-MM-dd");
            
            if(jComboBoxIDCourse.getSelectedItem().toString().equals("All")){
                jComboBoxIDCourse.removeAllItems();
                jComboBoxIDCourse.addItem("All");
                loadDataOnJTable();
                return;
            }
                         
            for (int i = 0; i < listCoursesRegistered.size(); i++) {
                String[] obj = listCoursesRegistered.get(i).split(";");
                if (obj[5].equals(jComboBoxIDCourse.getSelectedItem().toString())) {
                    String id_student = obj[0];
                    String student_name = obj[1] + " " + obj[2];
                    String student_birthday;

                    student_birthday = formatter1.format(formatter2.parse(obj[3]));
                    String gender = ("true".equals(obj[4])) ? "Male" : "Female";
                    String id_course = obj[5];

                    String course_name = obj[6];
                    String type = obj[7];
                    switch (type) {
                        case "KG":
                            type = "Kindergarten";
                            break;
                        case "KD":
                            type = "Kid";
                            break;
                        case "YT":
                            type = "Youth";
                            break;
                        case "ADU":
                            type = "Adult";
                            break;
                    }
                    Object[] ojb = {id_student, student_name, student_birthday, gender, id_course, course_name, type};
                    dftable.addRow(ojb);
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(ViewCoursesRegistered.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonFindActionPerformed

    public void setColor(javax.swing.JButton button) {
        button.setBackground(new java.awt.Color(115, 163, 239));
    }

    public void resetColor(javax.swing.JButton button) {
        button.setBackground(new java.awt.Color(12, 91, 160));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFind;
    private javax.swing.JComboBox<String> jComboBoxIDCourse;
    private javax.swing.JTable jDataTable;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCount;
    // End of variables declaration//GEN-END:variables
}
